"""VerifyEngine + workers.run_verify rubric-mode tests.

Exercises both:
  - rubric.json absent -> legacy LLM verifier path is used (LLM mocked)
  - rubric.json present -> VerifyEngine drives evaluators (no LLM call)
  - solution.json schema is the v0.2 form (axes list + weighted_score + summary)
"""
from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest

from agent_loop import models as models_mod
from agent_loop import workers
from agent_loop.config import Config
from agent_loop.state import TaskDir
from agent_loop.verify_engine import VerifyEngine, result_to_dict


def _fake_completion(text: str) -> SimpleNamespace:
    return SimpleNamespace(
        choices=[SimpleNamespace(message=SimpleNamespace(content=text))],
        usage=SimpleNamespace(prompt_tokens=5, completion_tokens=5),
    )


def _seed_task(tmp_path: Path, code: str) -> TaskDir:
    td = TaskDir(root=tmp_path, task_id="vt1")
    td.init()
    td.task_md_path().write_text("# Task\nImplement add", encoding="utf-8")
    (td.workspace_path() / "solution.py").write_text(code, encoding="utf-8")
    return td


# ---------- legacy path is preserved when no rubric.json ----------

def test_run_verify_legacy_when_no_rubric(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    td = _seed_task(tmp_path, "def add(a, b):\n    return a + b\n")
    payload = {
        "axes": {"correctness": 0.8},
        "weighted_score": 0.8,
        "evidence": "looks good",
        "issues": [],
    }
    monkeypatch.setattr(
        models_mod.litellm,
        "completion",
        lambda **kw: _fake_completion(json.dumps(payload)),
    )
    monkeypatch.setattr(models_mod.litellm, "completion_cost", lambda **_: 0.0)

    workers.run_verify(td, Config())
    sol = td.read_artifact("solution.json")
    assert isinstance(sol, dict)
    # legacy schema preserved
    assert sol["weighted_score"] == 0.8
    assert sol["evidence"] == "looks good"
    # no rubric.json was generated by the verifier itself
    assert not td.has_artifact("rubric.json")


# ---------- rubric path: pytest evaluator drives the score, no LLM call ----------

def test_run_verify_with_rubric_no_llm(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    td = _seed_task(tmp_path, "def add(a, b):\n    return a + b\n")
    rubric = {
        "axes": {
            "correctness": {
                "evaluator": "pytest",
                "weight": 0.6,
                "test": "assert add(1, 2) == 3\nassert add(0, 0) == 0\n",
            },
            "complexity": {
                "evaluator": "ast_grep",
                "weight": 0.4,
                "rule": ".index( not_in",
            },
        }
    }
    td.write_artifact("rubric.json", rubric)

    boom_count = {"n": 0}

    def boom(**_: Any) -> Any:
        boom_count["n"] += 1
        return _fake_completion("should not be called")

    monkeypatch.setattr(models_mod.litellm, "completion", boom)
    monkeypatch.setattr(models_mod.litellm, "completion_cost", lambda **_: 0.0)

    resp = workers.run_verify(td, Config())
    assert boom_count["n"] == 0  # zero LLM calls
    assert resp.cost_usd == 0.0
    assert resp.model.startswith("(verify_engine")

    sol = td.read_artifact("solution.json")
    assert isinstance(sol, dict)
    assert sol["weighted_score"] == 1.0
    assert isinstance(sol["axes"], list) and len(sol["axes"]) == 2
    names = {a["name"] for a in sol["axes"]}
    assert names == {"correctness", "complexity"}
    # all programmatic -> ground truth flagged
    assert all(a["is_ground_truth"] for a in sol["axes"])
    # summary fits in the Context Engine 200-char cap
    assert len(sol["summary"]) <= 200


# ---------- engine direct: weighted score arithmetic ----------

def test_verify_engine_weighted_arithmetic(tmp_path: Path) -> None:
    td = _seed_task(tmp_path, "def add(a, b):\n    return a + b\n")
    rubric = {
        "axes": {
            "good": {"evaluator": "pytest", "weight": 0.5, "test": "assert add(1,1)==2"},
            "bad": {"evaluator": "pytest", "weight": 0.5, "test": "assert add(1,1)==99"},
        }
    }
    result = VerifyEngine(td, Config()).evaluate(rubric)
    # 1.0 * 0.5 + 0.0 * 0.5 = 0.5
    assert result.weighted_score == pytest.approx(0.5)
    assert len(result.axes) == 2
    payload = result_to_dict(result)
    assert payload["weighted_score"] == pytest.approx(0.5)
    assert "good=1.00" in payload["summary"] and "bad=0.00" in payload["summary"]


# ---------- engine: empty rubric returns no axes ----------

def test_verify_engine_empty_rubric(tmp_path: Path) -> None:
    td = _seed_task(tmp_path, "x = 1\n")
    result = VerifyEngine(td, Config()).evaluate({})
    assert result.axes == []
    assert result.weighted_score == 0.0
    assert "no axes" in result.summary
